language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - travis_retry composer self-update
  - travis_retry composer install
  - phpenv rehash

script:
  - ./vendor/bin/phpunit --coverage-text